int mainDrive();
double inchesToDegrees(double inches);
void goForward();
void goBackward();
void turnLeft();
void turnRight();
void stop();
void forwardInches(double inches);
void backwardInches(double inches);
void turnDegrees(double deg);